# Autogenerated wrapper script for NanoVG_jll for i686-w64-mingw32
export compile_commands, libnanovg, libnanovggl2, libnanovggl3, libnanovggles2, libnanovggles3

using GLEW_jll
JLLWrappers.@generate_wrapper_header("NanoVG")
JLLWrappers.@declare_file_product(compile_commands)
JLLWrappers.@declare_library_product(libnanovg, "libnanovg.dll")
JLLWrappers.@declare_library_product(libnanovggl2, "libnanovggl2.dll")
JLLWrappers.@declare_library_product(libnanovggl3, "libnanovggl3.dll")
JLLWrappers.@declare_library_product(libnanovggles2, "libnanovggles2.dll")
JLLWrappers.@declare_library_product(libnanovggles3, "libnanovggles3.dll")
function __init__()
    JLLWrappers.@generate_init_header(GLEW_jll)
    JLLWrappers.@init_file_product(
        compile_commands,
        "share\\compile_commands.json",
    )

    JLLWrappers.@init_library_product(
        libnanovg,
        "bin\\libnanovg.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnanovggl2,
        "bin\\libnanovggl2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnanovggl3,
        "bin\\libnanovggl3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnanovggles2,
        "bin\\libnanovggles2.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnanovggles3,
        "bin\\libnanovggles3.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
