# Autogenerated wrapper script for NanoVG_jll for i686-linux-musl
export compile_commands, libnanovg, libnanovggl2, libnanovggl3, libnanovggles2, libnanovggles3

using GLEW_jll
JLLWrappers.@generate_wrapper_header("NanoVG")
JLLWrappers.@declare_file_product(compile_commands)
JLLWrappers.@declare_library_product(libnanovg, "libnanovg.so")
JLLWrappers.@declare_library_product(libnanovggl2, "libnanovggl2.so")
JLLWrappers.@declare_library_product(libnanovggl3, "libnanovggl3.so")
JLLWrappers.@declare_library_product(libnanovggles2, "libnanovggles2.so")
JLLWrappers.@declare_library_product(libnanovggles3, "libnanovggles3.so")
function __init__()
    JLLWrappers.@generate_init_header(GLEW_jll)
    JLLWrappers.@init_file_product(
        compile_commands,
        "share/compile_commands.json",
    )

    JLLWrappers.@init_library_product(
        libnanovg,
        "lib/libnanovg.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnanovggl2,
        "lib/libnanovggl2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnanovggl3,
        "lib/libnanovggl3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnanovggles2,
        "lib/libnanovggles2.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libnanovggles3,
        "lib/libnanovggles3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
